### ISSUE TITLE
Keuze afbeeldingen

### ISSUE THREAD

**Issue by Stefan-Espant** [driezie/look-and-feel-corporate-identity#2]
Kleine tip voor als je voor de opdrachtgever bezig bent. Zorg voor het gebruik van gepaste afbeeldingen dat betrekking heeft tot het uiteindelijke doel. In dit geval zou ik voorbeeld foto's gebruiken van huizen in plaats van je afgelopen zaterdagavond. 

[afbeelding](https://github.com/driezie/look-and-feel-corporate-identity/tree/main/assets/img/person.jpg)

**Comment by driezie** [comment]
Issue gefixed in commit [dfb05f73c299f04a2d90399990865a334bb5ae20](https://github.com/driezie/look-and-feel-corporate-identity/commit/dfb05f73c299f04a2d90399990865a334bb5ae20)
